name: obesetechapp
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you want to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  jwt_decoder: ^2.0.1
  animate_do: ^3.3.4  # Latest version as of now, check pub.dev for updates
  provider: ^6.1.2
  shared_preferences: ^2.2.3 
  fluttertoast: ^8.0.9 
  flutter_secure_storage: ^9.0.0
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  fl_chart: ^0.64.0
  image_picker: ^1.1.2
  google_fonts: ^6.2.1
  lucide_icons: ^0.257.0
  percent_indicator: ^4.2.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - lib/logo.png
    - lib/zt.jpg
    - lib/zf.jpg
    - lib/zm.jpg
    - lib/zk.jpg
    - lib/zp.jpg
    - lib/rt.jpg
    - lib/br.jpg
    - lib/po.jpg
    - lib/splash.jpg
    - lib/sch.jpg
    - lib/frz.jpg
    - lib/last.jpg
